---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: about
  label: About Us
  create: documents
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: services
  label: Services
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: volunteer
  label: Volunteer
  create: all
  match: "**/*"
  new_doc_ext: html
- type: document
  path: events.html
  label: Events
- type: directory
  path: partners
  label: Partners
  create: all
  match: "**/*"
- type: document
  path: donate.html
  label: Donate
- type: document
  path: index.html
  label: Index
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll build  --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
